
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ancho = 18;
  public static final int suma = 27;
  public static final int resta = 28;
  public static final int cuerpofin = 8;
  public static final int imprimir = 22;
  public static final int htmlinicio = 2;
  public static final int correo = 38;
  public static final int coma = 23;
  public static final int igual = 26;
  public static final int web = 39;
  public static final int identificador = 34;
  public static final int multiplicacion = 29;
  public static final int cuerpoinicio = 7;
  public static final int lista = 35;
  public static final int altura = 19;
  public static final int dos_puntos = 25;
  public static final int htmlfin = 3;
  public static final int numero = 40;
  public static final int encabezadofin = 5;
  public static final int pagina = 21;
  public static final int filafin = 16;
  public static final int EOF = 0;
  public static final int encabezadoinicio = 4;
  public static final int punto_coma = 24;
  public static final int comillas = 31;
  public static final int nombre = 36;
  public static final int tablainicio = 9;
  public static final int error = 1;
  public static final int listainicio = 11;
  public static final int numero_real = 41;
  public static final int imageninicio = 13;
  public static final int parentesis_c = 33;
  public static final int parentesis_a = 32;
  public static final int enlace = 17;
  public static final int titulo = 6;
  public static final int apellido = 37;
  public static final int filainicio = 15;
  public static final int listafin = 12;
  public static final int tablafin = 10;
  public static final int division = 30;
  public static final int imagenfin = 14;
  public static final int negrita = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "htmlinicio",
  "htmlfin",
  "encabezadoinicio",
  "encabezadofin",
  "titulo",
  "cuerpoinicio",
  "cuerpofin",
  "tablainicio",
  "tablafin",
  "listainicio",
  "listafin",
  "imageninicio",
  "imagenfin",
  "filainicio",
  "filafin",
  "enlace",
  "ancho",
  "altura",
  "negrita",
  "pagina",
  "imprimir",
  "coma",
  "punto_coma",
  "dos_puntos",
  "igual",
  "suma",
  "resta",
  "multiplicacion",
  "division",
  "comillas",
  "parentesis_a",
  "parentesis_c",
  "identificador",
  "lista",
  "nombre",
  "apellido",
  "correo",
  "web",
  "numero",
  "numero_real"
  };
}

